### ISSUE TITLE
Fails when there is overlap between sections

### ISSUE THREAD

**Issue by pukkandan** [faissaloo/SponSkrub#11]
Eg:  `sponskrub A4yJwWTVoCU test.webm out.webm -chapter  -include-outros -include-interactions`

In the above video, there is a tiny overlap between the `outro` and `interaction` sections. This causes marking the chapters to fail with the error: 

```
[ffmetadata @ 000001f9b6880600] Chapter end time 397 before start 399
lgqphs-metadata.ffm: Cannot allocate memory
There was an issue generating the output file, is ffmpeg installed? This could be a bug
```

PS: If the overlap gets fixed in the database, the example will become obsolete.

**Comment by faissaloo** [comment]
So we need to decide how we want to resolve them, my thinking is that we favor the section that's being started over the previous section continuing, what do you think?

**Comment by pukkandan** [comment]
I think either way would be fine since all such instances I have encountered are just a few seconds atmost. Ideally, the sections with most likes should be kept imo. But that is honestly unnecessarily complicated. The important thing is just to make sure that the program doesn't fail in such situations. Exactly what section those few seconds fall into doesn't really matter.

**Comment by faissaloo** [comment]
Just pushed a fix for this, mind taking it for a spin?

**Comment by pukkandan** [comment]
I was quite busy irl. Ive updated with the new version and will let you know if I see any issues

**Comment by faissaloo** [comment]
No need to make excuses for being busy we've all got stuff to do it's cool
