### ISSUE TITLE
[Info] Direct integration with youtube-dlc

### ISSUE THREAD

**Issue by pukkandan** [faissaloo/SponSkrub#14]
Hi,
I just want to let you know that I am trying to integrate this program directly into `youtube-dlc` as a PostProcessor. https://github.com/blackjack4494/yt-dlc/pull/212

I didn't know how to PM on github, which is why I created an issue

**Comment by faissaloo** [comment]
Wow, that's pretty based dude, I've just subscribed to that PR thanks for letting me know
