### ISSUE TITLE
Discussion: Rename `ydl`

### ISSUE THREAD

**Issue by JanPokorny** [faissaloo/SponSkrub#15]
The command `ydl` has a very generic name, with no mention of SponSkrub in the name, which may cause name conflicts and confusion. In my opinion, it should be renamed. `sponskrub-ydl` sounds right, although I don't have a strong opinion on what is the best name.

**Comment by faissaloo** [comment]
`ydl` was chosen because it's quick to type, if you have a similarly short name I'm open to hearing it, what do you think of `das` (download and scrub [youtube videos])? It's all on the homerow in dvorak

**Comment by JanPokorny** [comment]
In my opinion, being quick to type should come after readability in scripts and general command discoverability. Also, having the same prefix (like `sponskrub-`) helps with tab expansion. If the user types the command often (so often that they actually care which keys are on the homerow on their keyboard layout...), they will simply spend 20 seconds creating an alias for it as they see pleasing.

**Comment by faissaloo** [comment]
Considering I actually already have an alias for it that's actually a really good point, I don't like `sponskrub-ydl` but the prefix is a good idea, if long names aren't an issue how about `sponskrub-youtube-dl`?

**Comment by JanPokorny** [comment]
I looked up some other `youtube-dl` wrappers and they mostly use the `youtube-dl-*` structure, which makes sense considering that the wrapper is basically "youtube-dl but with extra steps". So what about `youtube-dl-sponskrub`?

**Comment by faissaloo** [comment]
Fixed in https://github.com/faissaloo/SponSkrub/commit/fa2a2e6f5f981862f967f7bb97ef11d407d1804b
