### ISSUE TITLE
Error while downloading video

### ISSUE THREAD

**Issue by jakiisheep** [faissaloo/SponSkrub#17]
I tried downloading a video, and it gave me an error. mv is not recognized bla bla. Because windows does not have mv, you could probably move it with move rather than mv

**Comment by pukkandan** [comment]
As a workaround, make a file `mv.cmd` with the contents `@move %*` and put it in the same folder as sponskrub

**Comment by faissaloo** [comment]
Hi, this might be fixed now as a result of the changes I made for #18, that said this project doesn't support Windoze so I'll be closing this.
