### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by mrdschrute** [faissaloo/SponSkrub#31]
I get the output below when I try to build SponSkrub. Am I doing something wrong?

Thanks

dub build :sponskrub

`Performing "debug" build using ldc2 for x86_64.
sponskrub:sponskrub ~master: building configuration ""...
src/sponskrub/sponsorblock.d(45,30): Error: undefined identifier JSONType
src/sponskrub/sponsorblock.d(47,37): Error: undefined identifier JSONType
ldc2 failed with exit code 1.
`

DUB version 1.23.0, built on Sep 25 2020

**Comment by faissaloo** [comment]
Use DMD (GDC might also work I haven't tried), D's JSON library is broken in LDC for some reason

**Comment by faissaloo** [comment]
ded ishue
