### ISSUE TITLE
Windows binaries in the releases would be super rad

### ISSUE THREAD

**Issue by Leonetienne** [faissaloo/SponSkrub#38]

**Comment by Leonetienne** [comment]
unless you're too based that is.

**Comment by faissaloo** [comment]
we don't do that here, see #13

**Comment by Leonetienne** [comment]
Is it a technical issue or just general unprofessionalness (in terms of just hating on a specific OS for no particular reason) ? 

Anyway, 
![thanos](https://user-images.githubusercontent.com/40911701/130526168-d195a2a3-7963-4a44-aba0-8d397763377a.gif)

**Comment by faissaloo** [comment]
It's two things:  
 - I don't have Windows, and I'm not going to put myself through the pain of Windows dev again, it's an operating system written by insane people  
 - Windows is a malicious operating system that people shouldn't use

**Comment by craigbarnes** [comment]
> Is it a technical issue or just general unprofessionalness (in terms of just hating on a specific OS for no particular reason) ?

![1628631879579](https://user-images.githubusercontent.com/494077/144939838-9c4dd3c8-7741-41ed-8093-5a16b286028e.png)
