### ISSUE TITLE
Doesn't work when video ID starts with a -

### ISSUE THREAD

**Issue by pukkandan** [faissaloo/SponSkrub#8]
Eg: `sponskrub "-0PyDhv6jlA" test.webm test2.webm`
The id is detected as a switch when it starts with a `-`.

`youtube-dl` uses a switch `--` to force such ids as url. 
Eg: `youtube-dl -0PyDhv6jlA` doesn't work, but `youtube-dl -- -0PyDhv6jlA` does.
It'd be great if you could implement a similar feature

**Comment by faissaloo** [comment]
Yeah `--` seems to be the standard Unix way of preventing things from being parsed as flags thank for pointing that out, I'll probably look into next weekend, right now I need sleep fam goodnight

**Comment by pukkandan** [comment]
I have created a pull request.

I have no experience with D-Lang, so make sure to review the code before you merge.

**Comment by faissaloo** [comment]
Thanks a ton!  
Also I just saw what that video id was
![image](https://user-images.githubusercontent.com/8840681/94460897-4e558a00-01b1-11eb-98e5-c86f85cc5065.png)
